name: Build & Publish
on:
  push:
    branches: [main]
jobs:
  binary:
    name: Binary
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            rustflags: -C linker=aarch64-linux-gnu-gcc
            packages: gcc-aarch64-linux-gnu
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y ${{ matrix.packages }}
        if: matrix.packages
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.target }}

      - name: Build
        run: cargo --locked build --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: ${{ matrix.rustflags }}

      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: cfme-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/cfme${{ matrix.ext }}
